##Read Image

In [64]:
import h5py
import numpy as np
from random import shuffle

In [65]:
fname = "/home/xca64/remote/GitHub/colorP/dataSet/geler/Gehler_Extras/Illuminants.txt"
with open(fname) as f:
    content = f.readlines()

In [56]:
print (content[1][:-3]).split(',')
print "/local-scratch/xca64/geler/source/" + content[3][:-2]

['0.0483994', ' 0.0427776', ' 0.0404933']
/local-scratch/xca64/geler/source/IMG_0282.tiff


In [66]:
shuffle_index = list(range(len(content)/3))
shuffle(shuffle_index)
print type(shuffle_index[1])

<type 'int'>


In [67]:
illu = np.zeros([len(content)/3,3])
src = []
for i in range(len(content)/3):
    illu[i, :] = np.array([float(x) for x in ((content[i*3+1][:-3]).split(','))])
    src.append("/local-scratch/xca64/geler/source/" + content[i*3][:-2] + " 0\n")

In [59]:
print len(illu)
print np.shape(illu[:50,:])

482
(50, 3)


#Save data to h5

In [70]:
illu_train = np.zeros([2*len(content)/9,3])
illu_test = np.zeros([len(content)/3-2*len(content)/9,3])
src_train = []
src_test = []
for i in range(len(content)/3):
    #print type(i)
    #print type(shuffle_index[i])
    if i < 2*len(content)/9:
        illu_train[i, :] = illu[shuffle_index[i], :]
        src_train.append(src[shuffle_index[i]])
    else:
        illu_test[i-2*len(content)/9, :] = illu[shuffle_index[i], :]
        src_test.append(src[shuffle_index[i]])
print len(illu_train)
print len(illu_test)

321
161


In [68]:


f = open('/home/xca64/remote/data/train_src.txt', 'w')
for i in range(len(src_train)):
    f.write(src_train[i])
f.close()
ft = open('/home/xca64/remote/data/test_src.txt', 'w')
for i in range(len(src_test)):
    ft.write(src_test[i])
ft.close()
with h5py.File('/home/xca64/remote/data/test_ill.h5') as h:
    h['illu'] = illu_test
with h5py.File('/home/xca64/remote/data/train_ill.h5') as h:
    h['illu'] = illu_train

#Save FileName

In [6]:
print "/home/xca64/remote/data/"+content[0]

/home/xca64/remote/data/IMG_0281.tiff,



In [8]:
with open('/home/xca64/remote/data/train_gehler_482.txt','w') as f:
    for i in range(482):
        f.write( '/local-scratch/xca64/geler/source/'+content[i*3][:-2] + ' ' + str(i+1) + ' \n')

In [63]:
with h5py.File('/home/xca64/remote/data/test_ill.h5') as h:
    print h['illu'][()]
    

[[ 0.2696086  0.241372   0.2274181]
 [ 0.0381052  0.0338343  0.0314889]
 [ 0.22774    0.2021193  0.1882904]
 [ 0.062638   0.0428023  0.0242889]
 [ 0.2095521  0.1911319  0.1826869]
 [ 0.0947137  0.0823927  0.0733981]
 [ 0.0189412  0.017761   0.0174274]
 [ 0.2015218  0.1905255  0.1910462]
 [ 0.0886967  0.0842913  0.0855299]
 [ 0.1086819  0.1049114  0.0909246]
 [ 0.2486533  0.2317721  0.2266697]
 [ 0.1914388  0.1805963  0.1805519]
 [ 0.0460472  0.0398007  0.035594 ]
 [ 0.0403125  0.0186989  0.0059918]
 [ 0.2348294  0.2184106  0.2017134]
 [ 0.0810707  0.0381836  0.0123756]
 [ 0.0368757  0.0341521  0.0336643]
 [ 0.0616159  0.0557647  0.0524742]
 [ 0.0595031  0.0538915  0.0513607]
 [ 0.1880026  0.1193956  0.0447487]
 [ 0.0642806  0.0603353  0.059548 ]
 [ 0.2784743  0.271433   0.2758245]
 [ 0.1153575  0.1058642  0.0998305]
 [ 0.154395   0.1350137  0.1220313]
 [ 0.3750503  0.3116651  0.2673694]
 [ 0.1535335  0.1416412  0.1382597]
 [ 0.4491794  0.3898337  0.3416745]
 [ 0.0848563  0.0694545  0.0

In [34]:
with open('/local-scratch/xca64/tmp/caffe-master/examples/my_img_preprocess/train_gehler_482.txt','w') as f:
    for i in range(482):
        f.write( content[i*3][:-2] + ' 0 \n')

#Read Gehler Mean data

In [39]:
import caffe #% suppose caffe is already in the path of Python
import numpy as np
import sys

blob = caffe.proto.caffe_pb2.BlobProto()
data = open( '/local-scratch/xca64/tmp/caffe-master/examples/my_img_preprocess/geler_482_mean.binaryproto' , 'rb' ).read()
blob.ParseFromString(data)
arr = np.array( caffe.io.blobproto_to_array(blob) )
#arr.shape % check the shape of arr


In [44]:
print np.max(arr)


32.0892105103
