##Read Image

In [8]:
import h5py
import numpy as np
#from random import shuffle
import os

In [10]:
# fname = "/home/xca64/remote/GitHub/colorP/dataSet/geler/Gehler_Extras/Illuminants.txt"
# with open(fname) as f:
#     content = f.readlines()
# fname_src = "/home/xca64/remote/data/shi_funt_filelist.txt"
# with open(fname_src) as f:
#     content_src = f.readlines()
# fname_illu = "/home/xca64/remote/data/shi_funt_illu.txt"
# with open(fname_illu) as f:
#     content_illu = f.readlines()
# fname_src = "/home/xca64/remote/data/geler_filelist.txt"
# with open(fname_src) as f:
#     content_src = f.readlines()
# fname_illu = "/home/xca64/remote/data/geler_illu.txt"
# with open(fname_illu) as f:
#     content_illu = f.readlines()
fname_src = "/home/xca64/remote/data/grayBall_filelist.txt"
with open(fname_src) as f:
    content_src = f.readlines()
fname_illu = "/home/xca64/remote/data/grayBall_illu.txt"
with open(fname_illu) as f:
    content_illu = f.readlines()

In [13]:
#print (content[1][:-3]).split(',')
#print "/local-scratch/xca64/geler/source/" + content[3][:-2]
print content_illu[0][:-2].split("\t")
print content_src[0][:-1]
print len(content_illu)

['0.295976000000000', '0.331589000000000', '0.37243500000000']
Source_Image/ApacheTrail/00000.jpg
11346


In [ ]:
# shuffle_index = list(range(len(content)/3))
# shuffle(shuffle_index)
# print type(shuffle_index[1])

In [12]:
illu = np.zeros([len(content_src),3]) # len(content)/3
src = []
#f = open('/home/xca64/remote/data/shi_funt_src.txt', 'w')
#f = open('/home/xca64/remote/data/geler_src.txt', 'w')
f = open('/home/xca64/remote/data/grayBall_src.txt', 'w')
for i in range(len(content_src)):
    #illu[i, :] = np.array([float(x) for x in ((content[i*3+1][:-3]).split(','))])
    #src.append("/local-scratch/xca64/geler/source/" + content[i*3][:-2] + " " + str(i)+"\n")
    illu[i, :] = np.array([float(x) for x in ((content_illu[i])[:-2].split("\t"))])
    #src.append("/local-scratch/xca64/shi_funt_new" + content_src[i][:-1] + " " + str(i)+"\n")
    #src.append("/local-scratch/xca64/geler/source/" + content_src[i][:-2] + " " + str(i)+"\n")
    src.append("/local-scratch/xca64/grayBall/" + content_src[i][:-1] + " " + str(i)+"\n")
    f.write(src[i])
f.close()

In [ ]:
print len(illu)
print np.shape(illu[:50,:])

#Save data to h5

In [14]:
#seprater = 2*len(content_src)/3 # len(content)/9
seprater = 4*len(content_src)/5 
#print(seprater)
illu_train = illu[:seprater,:]
illu_test = illu[seprater:,:]
src_train = src[:seprater]
src_test = src[seprater:]
# for i in range(len(content)/3):
#     #print type(i)
#     #print type(shuffle_index[i])
#     if i < 2*len(content)/9:
#         illu_train[i, :] = illu[shuffle_index[i], :]
#         src_train.append(src[shuffle_index[i]])
#     else:
#         illu_test[i-2*len(content)/9, :] = illu[shuffle_index[i], :]
#         src_test.append(src[shuffle_index[i]])
print len(illu_train)
print len(illu_test)
print len(src_train)
print len(src_test)

7564
3782
7564
3782


In [15]:
dataPath = "/home/xca64/remote/data/"
fileName = "test_ill.h5"
rmCommand = "rm -rf " +  dataPath + fileName 
os.system(rmCommand)
fileName = "train_ill.h5"
rmCommand = "rm -rf " +  dataPath + fileName 
os.system(rmCommand)

f = open('/home/xca64/remote/data/train_src.txt', 'w')
for i in range(len(src_train)):
    f.write(src_train[i])
f.close()
ft = open('/home/xca64/remote/data/test_src.txt', 'w')
for i in range(len(src_test)):
    ft.write(src_test[i])
ft.close()


with h5py.File('/home/xca64/remote/data/test_ill.h5') as h:
    h['illu'] = illu_test
with h5py.File('/home/xca64/remote/data/train_ill.h5') as h:
    h['illu'] = illu_train

#Save FileName

In [ ]:
print "/home/xca64/remote/data/"+content[0]

In [ ]:
with open('/home/xca64/remote/data/train_gehler_482.txt','w') as f:
    for i in range(482):
        f.write( '/local-scratch/xca64/geler/source/'+content[i*3][:-2] + ' ' + str(i+1) + ' \n')

In [16]:
with h5py.File('/home/xca64/remote/data/train_ill.h5') as h:
    print h['illu'][()]
    

[[ 0.295976  0.331589  0.372435]
 [ 0.298753  0.332463  0.368784]
 [ 0.301102  0.331784  0.367114]
 ..., 
 [ 0.43492   0.337777  0.227303]
 [ 0.435385  0.337252  0.227363]
 [ 0.401349  0.345852  0.252799]]


In [ ]:
with open('/local-scratch/xca64/tmp/caffe-master/examples/my_img_preprocess/train_gehler_482.txt','w') as f:
    for i in range(482):
        f.write( content[i*3][:-2] + ' 0 \n')

#Read Gehler Mean data

In [ ]:
import caffe #% suppose caffe is already in the path of Python
import numpy as np
import sys

blob = caffe.proto.caffe_pb2.BlobProto()
data = open( '/local-scratch/xca64/tmp/caffe-master/examples/my_img_preprocess/geler_482_mean.binaryproto' , 'rb' ).read()
blob.ParseFromString(data)
arr = np.array( caffe.io.blobproto_to_array(blob) )
#arr.shape % check the shape of arr


In [ ]:
print np.max(arr)
