##Read Image

In [ ]:
import h5py
import numpy as np

In [ ]:
fname = "/home/xca64/remote/GitHub/colorP/dataSet/geler/Gehler_Extras/Illuminants.txt"
with open(fname) as f:
    content = f.readlines()

In [ ]:
print (content[1][:-3]).split(',')

In [ ]:
illu = np.zeros([len(content)/3,3])
for i in range(len(content)/3):
    illu[i, :] = np.array([float(x) for x in ((content[i*3+1][:-3]).split(','))])


In [ ]:
print len(illu)
print np.shape(illu[:50,:])

#Save data to h5

In [ ]:
illu = illu[:50,:]
with h5py.File('/home/xca64/remote/data/illu_gehler_50.h5') as h:
    h['illu'] = illu

#Save FileName

In [ ]:
print "/home/xca64/remote/data/"+content[0]

In [ ]:
with open('/home/xca64/remote/data/train_gehler_50.txt','w') as f:
    for i in range(50):
        f.write( '/home/xca64/remote/GitHub/colorP/dataSet/geler/source/'+content[i*3][:-2] + ' 0 \n')

In [30]:
with h5py.File('/home/xca64/remote/data/illu_gehler_50.h5') as h:
    print h['illu'][()]

[[ 0.0483994  0.0427776  0.0404933]
 [ 0.0406068  0.0364151  0.035649 ]
 [ 0.1531402  0.1356553  0.1286482]
 [ 0.1292548  0.1173989  0.1107552]
 [ 0.1236585  0.1087753  0.1015189]
 [ 0.0664755  0.0592282  0.0546045]
 [ 0.0947137  0.0823927  0.0733981]
 [ 0.132211   0.1183176  0.1075993]
 [ 0.0393706  0.0339711  0.0312228]
 [ 0.0327561  0.0289142  0.0276223]
 [ 0.0848609  0.072155   0.0624354]
 [ 0.0765817  0.0654978  0.0562368]
 [ 0.0553069  0.0492734  0.0464582]
 [ 0.1152329  0.1045922  0.09878  ]
 [ 0.0745489  0.0619331  0.0548576]
 [ 0.0362815  0.0297022  0.0239729]
 [ 0.0727918  0.066176   0.063148 ]
 [ 0.0473708  0.042198   0.0394276]
 [ 0.0815719  0.0710234  0.0644596]
 [ 0.115931   0.1019348  0.0924003]
 [ 0.1197433  0.1055204  0.0945449]
 [ 0.0496322  0.0440014  0.0403473]
 [ 0.0898297  0.0791961  0.0724874]
 [ 0.0738529  0.0668713  0.0634783]
 [ 0.0911424  0.0802126  0.0733525]
 [ 0.1814054  0.160593   0.1464693]
 [ 0.2288796  0.2027446  0.1838481]
 [ 0.0737138  0.0625222  0.0