##Read Image

In [1]:
import h5py
import numpy as np
#from random import shuffle
import os

In [2]:
fname = "/home/xca64/remote/GitHub/colorP/dataSet/geler/Gehler_Extras/Illuminants.txt"
with open(fname) as f:
    content = f.readlines()
# fname_src = "/home/xca64/remote/data/shi_funt_filelist.txt"
# with open(fname_src) as f:
#     content_src = f.readlines()
# fname_illu = "/home/xca64/remote/data/shi_funt_illu.txt"
# with open(fname_illu) as f:
#     content_illu = f.readlines()
# fname_src = "/home/xca64/remote/data/geler_filelist.txt"
# with open(fname_src) as f:
#     content_src = f.readlines()
# fname_illu = "/home/xca64/remote/data/geler_illu.txt"
# with open(fname_illu) as f:
#     content_illu = f.readlines()
# fname_src = "/home/xca64/remote/data/grayBall_filelist.txt"
# with open(fname_src) as f:
#     content_src = f.readlines()
# fname_illu = "/home/xca64/remote/data/grayBall_illu.txt"
# with open(fname_illu) as f:
#     content_illu = f.readlines()

In [3]:
#print (content[1][:-3]).split(',')
#print "/local-scratch/xca64/geler/source/" + content[3][:-2]
# print content_illu[0][:-2].split("\t")
# print content_src[0][:-1]
print len(content)

1446


In [4]:
# shuffle_index = list(range(len(content)/3))
# shuffle(shuffle_index)
# print type(shuffle_index[1])

In [5]:
illu = np.zeros([len(content)/3,3]) #  len(content_src)
src = []
#f = open('/home/xca64/remote/data/shi_funt_src.txt', 'w')
#f = open('/home/xca64/remote/data/geler_src.txt', 'w')
#f = open('/home/xca64/remote/data/grayBall_src.txt', 'w')
for i in range(len(content)/3): #  len(content_src)
    illu[i, :] = np.array([float(x) for x in ((content[i*3+1][:-3]).split(','))])
    src.append("/local-scratch/xca64/geler/source/" + content[i*3][:-2] + " " + str(i)+"\n")
    #illu[i, :] = np.array([float(x) for x in ((content_illu[i])[:-2].split("\t"))])
    #src.append("/local-scratch/xca64/shi_funt_new" + content_src[i][:-1] + " " + str(i)+"\n")
    #src.append("/local-scratch/xca64/geler/source/" + content_src[i][:-2] + " " + str(i)+"\n")
    #src.append("/local-scratch/xca64/grayBall/" + content_src[i][:-1] + " " + str(i)+"\n")
    #f.write(src[i])
#f.close()

In [6]:
#print len(illu)
#print np.shape(illu[:50,:])
illu = (illu.transpose() / (np.sum(illu,axis = 1)).transpose()).transpose()
print illu

[[ 0.36758024  0.3248842   0.30753556]
 [ 0.36040184  0.3231988   0.31639935]
 [ 0.36685234  0.3249667   0.30818096]
 ..., 
 [ 0.56068848  0.30772501  0.13158652]
 [ 0.55108562  0.30718419  0.14173019]
 [ 0.50293817  0.31712636  0.17993547]]


#Save data to h5

In [7]:
seprater = 2* len(content)/9 #len(content_src)/3 
#print(seprater)
illu_train = illu[:seprater,:]
illu_test = illu[seprater:,:]
src_train = src[:seprater]
src_test = src[seprater:]
# for i in range(len(content)/3):
#     #print type(i)
#     #print type(shuffle_index[i])
#     if i < 2*len(content)/9:
#         illu_train[i, :] = illu[shuffle_index[i], :]
#         src_train.append(src[shuffle_index[i]])
#     else:
#         illu_test[i-2*len(content)/9, :] = illu[shuffle_index[i], :]
#         src_test.append(src[shuffle_index[i]])
print len(illu_train)
print len(illu_test)
print len(src_train)
print len(src_test)

321
161
321
161


In [9]:
#print illu_train
print (np.round(illu_train*255)[:,0])

[  94.   92.   94.   92.   94.   94.   96.   94.   96.   94.   99.   98.
   93.   92.   99.  103.   92.   94.   96.   95.   95.   94.   95.   92.
   95.   95.   95.   97.   94.   95.   96.   95.   94.   95.   97.   96.
  101.   94.   94.   97.   95.   95.   92.   92.   92.   93.   93.   93.
   93.  100.   94.   93.   92.   94.   96.   93.   96.   92.  109.  108.
  101.   98.  101.  101.  103.   99.  100.   94.   92.   93.   93.   93.
   94.   94.   92.   93.   93.   93.   94.   99.   92.   97.  100.   92.
   89.   88.   97.   95.  101.   96.  101.   96.   97.   96.  100.  101.
   94.   94.   94.   95.   94.   96.   97.   94.   94.  112.   94.   96.
  101.   96.  100.   91.  106.  103.   94.   94.   93.   95.   94.   93.
   95.   94.   94.  113.  103.   91.   95.  115.   98.  103.  107.   95.
  100.   90.  103.   92.   92.   87.  102.   88.   92.  101.   93.   85.
   88.   87.   85.   83.   89.   79.   93.   91.  101.  110.  122.  131.
  133.  113.  105.  100.   97.  103.   93.  102.  1

In [10]:
dataPath = "/home/xca64/remote/data/"
fileName = "test_ill.h5"
rmCommand = "rm -rf " +  dataPath + fileName 
os.system(rmCommand)
fileName = "train_ill.h5"
rmCommand = "rm -rf " +  dataPath + fileName 
os.system(rmCommand)

f = open('/home/xca64/remote/data/train_src.txt', 'w')
for i in range(len(src_train)):
    f.write(src_train[i])
f.close()
ft = open('/home/xca64/remote/data/test_src.txt', 'w')
for i in range(len(src_test)):
    ft.write(src_test[i])
ft.close()


with h5py.File('/home/xca64/remote/data/test_ill.h5') as h:
    h['illu_R'] = (np.round(illu_test*255)[:,0])#.astype(np.uint8)
    h['illu_G'] = (np.round(illu_test*255)[:,1])#.astype(np.uint8)
    h['illu_B'] = (np.round(illu_test*255)[:,2])#.astype(np.uint8)

with h5py.File('/home/xca64/remote/data/train_ill.h5') as h:
    h['illu_R'] = (np.round(illu_test*255)[:,0])#.astype(np.uint8)
    h['illu_G'] = (np.round(illu_test*255)[:,1])#.astype(np.uint8)
    h['illu_B'] = (np.round(illu_test*255)[:,2])#.astype(np.uint8)

#Save FileName

In [ ]:
print "/home/xca64/remote/data/"+content[0]

In [ ]:
with open('/home/xca64/remote/data/train_gehler_482.txt','w') as f:
    for i in range(482):
        f.write( '/local-scratch/xca64/geler/source/'+content[i*3][:-2] + ' ' + str(i+1) + ' \n')

In [ ]:
with h5py.File('/home/xca64/remote/data/train_ill.h5') as h:
    r = h['illu_B'][()]
    print (np.array([r,r]).transpose())[1,:]
    

In [ ]:
with open('/local-scratch/xca64/tmp/caffe-master/examples/my_img_preprocess/train_gehler_482.txt','w') as f:
    for i in range(482):
        f.write( content[i*3][:-2] + ' 0 \n')

#Read Gehler Mean data

In [ ]:
import caffe #% suppose caffe is already in the path of Python
import numpy as np
import sys

blob = caffe.proto.caffe_pb2.BlobProto()
data = open( '/local-scratch/xca64/tmp/caffe-master/examples/my_img_preprocess/geler_482_mean.binaryproto' , 'rb' ).read()
blob.ParseFromString(data)
arr = np.array( caffe.io.blobproto_to_array(blob) )
#arr.shape % check the shape of arr


In [ ]:
print np.max(arr)
